import Head from "next/head";
import Layout from "../src/components/Layout";

export default function Home() {
  return (
    <div className="h-screen text-center">
      <Head>
        <title>Next Redux Saga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="font-bold text-gray-800 text-8xl mt-32 hover:text-indigo-600">Next Redux Saga</h1>
      <p className="text-indigo-400 text-sm font-mono mt-6 font-bold">Country CRUD With Next, Redux-Saga, Axios, etc.</p>
    </div>
  );
}
